# -*- coding: utf-8 -*-
"""BERT_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15LlDyM_lSW6s27TCW2t9270g5D2_k6nN
"""

import pandas as pd
import tensorflow as tf
import transformers
from sklearn.model_selection import train_test_split
import numpy as np

with tf.device('/device:GPU:0'):
  df = pd.read_csv("new_train.csv", on_bad_lines="skip")
  print(df.head())
  # Tokenizer
  tokenizer = transformers.BertTokenizer.from_pretrained("bert-base-uncased")
  sample_texts = df["text"].tolist()

  # Tokenizing texts and returning as tensors
  x_encoded = tokenizer(
      sample_texts,
      padding="max_length",
      truncation=True,
      max_length=128,
      return_tensors="tf"
  )

  input_ids = x_encoded["input_ids"]
  attention_mask = x_encoded["attention_mask"]

  # Check shapes
  print(input_ids.shape, attention_mask.shape)

  # y set (labels)
  y = df["label"].values



import numpy as np
from sklearn.model_selection import train_test_split

with tf.device('/device:GPU:0'):
    X_train, X_val, y_train, y_val = train_test_split(
        np.array(x_encoded["input_ids"]),  # Convert to NumPy array
        np.array(y),  # Ensure y is also a NumPy array
        test_size=0.2,
        random_state=42
    )

with tf.device('/device:GPU:0'):
  train_dataset = tf.data.Dataset.from_tensor_slices((X_train, y_train)).batch(16)
  val_dataset = tf.data.Dataset.from_tensor_slices((X_val, y_val)).batch(16)

  model = transformers.TFBertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=len(set(y)))

with tf.device('/device:GPU:0'):
  num_train_steps = len(train_dataset) * 3
  lr_scheduler = tf.keras.optimizers.schedules.PolynomialDecay(initial_learning_rate=5e-5, end_learning_rate=0.0, decay_steps=num_train_steps)
  optimizer = tf.keras.optimizers.legacy.Adam(learning_rate=lr_scheduler)

  model.compile(optimizer=optimizer, loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=["accuracy"])
  model.summary()

with tf.device('/device:GPU:0'):
  model.fit(train_dataset, validation_data=val_dataset, epochs=3)